# Generated by Django 5.2.16 on 2026-07-18 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookshelf", "0001_initial"),
        ("novels", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookshelfitem",
            name="last_read_chapter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="novels.chapter",
            ),
        ),
        migrations.AddField(
            model_name="bookshelfitem",
            name="novel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookshelf_items",
                to="novels.novel",
            ),
        ),
    ]
