# Generated by Django 5.2.16 on 2026-07-18 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookshelf", "0002_initial"),
        ("novels", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="bookshelfitem",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookshelf_items",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="readinghistory",
            name="chapter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reading_histories",
                to="novels.chapter",
            ),
        ),
        migrations.AddField(
            model_name="readinghistory",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reading_histories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="bookshelfitem",
            index=models.Index(
                fields=["user", "updated_at"], name="bookshelf_b_user_id_275bd8_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="bookshelfitem",
            unique_together={("user", "novel")},
        ),
        migrations.AlterUniqueTogether(
            name="readinghistory",
            unique_together={("user", "chapter")},
        ),
    ]
