# Generated by Django 5.2.16 on 2026-07-18 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "volume_title",
                    models.CharField(blank=True, default="默认卷", max_length=120),
                ),
                ("chapter_number", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("word_count", models.PositiveIntegerField(default=0)),
                (
                    "publish_status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("scheduled", "定时发布"),
                            ("published", "已发布"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("pending", "待审核"),
                            ("approved", "已通过"),
                            ("rejected", "已拒绝"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["chapter_number"],
            },
        ),
        migrations.CreateModel(
            name="Novel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=230, unique=True)),
                ("cover_url", models.URLField(blank=True, default="")),
                ("summary", models.TextField(blank=True, default="")),
                ("category", models.CharField(default="未分类", max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[("ongoing", "连载中"), ("completed", "已完结")],
                        default="ongoing",
                        max_length=16,
                    ),
                ),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("pending", "待审核"),
                            ("approved", "已通过"),
                            ("rejected", "已拒绝"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("word_count", models.PositiveIntegerField(default=0)),
                ("click_count", models.PositiveIntegerField(default=0)),
                ("favorite_count", models.PositiveIntegerField(default=0)),
                (
                    "rating_avg",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                ("rating_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, unique=True)),
            ],
        ),
    ]
