# Generated by Django 5.2.16 on 2026-07-18 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("novels", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="novel",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="novels",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="chapter",
            name="novel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chapters",
                to="novels.novel",
            ),
        ),
        migrations.AddField(
            model_name="novel",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="novels", to="novels.tag"
            ),
        ),
        migrations.AddIndex(
            model_name="chapter",
            index=models.Index(
                fields=["novel", "review_status", "publish_status"],
                name="novels_chap_novel_i_ab8bc9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="chapter",
            index=models.Index(
                fields=["scheduled_at"], name="novels_chap_schedul_c715c7_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="chapter",
            unique_together={("novel", "chapter_number")},
        ),
        migrations.AddIndex(
            model_name="novel",
            index=models.Index(
                fields=["review_status", "updated_at"],
                name="novels_nove_review__9bffaa_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="novel",
            index=models.Index(
                fields=["click_count", "favorite_count"],
                name="novels_nove_click_c_d05073_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="novel",
            index=models.Index(
                fields=["category"], name="novels_nove_categor_b4610a_idx"
            ),
        ),
    ]
